services:
  - type: web
    name: stockanalyser
    env: python
    runtime: python
    buildCommand: pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
